# Generated by Django 3.1.4 on 2021-03-15 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='checkIn',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='checkOut',
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='hotelPhone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
