# Generated by Django 3.1.4 on 2021-03-15 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auto_20210315_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotelName',
            field=models.CharField(max_length=30),
        ),
    ]
